set_property IOSTANDARD LVCMOS33 [get_ports {voltage_out_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {voltage_out_tri_io[0]}]
set_property PACKAGE_PIN L18 [get_ports {voltage_out_tri_io[1]}]
set_property PACKAGE_PIN V8 [get_ports {voltage_out_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ltrig_out]
set_property PACKAGE_PIN V12 [get_ports ltrig_out]


set_property IOSTANDARD LVCMOS33 [get_ports {RCLEAR_tri_o[0]}]
set_property PACKAGE_PIN W12 [get_ports {RCLEAR_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGDATEN_tri_o[0]}]
set_property PACKAGE_PIN R6 [get_ports {VGDATEN_tri_o[0]}]
set_property PACKAGE_PIN U11 [get_ports {VGSDATA_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGSDATA_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[0]}]
set_property PACKAGE_PIN L17 [get_ports {adc9226_data[0]}]
set_property PACKAGE_PIN P16 [get_ports {adc9226_data[1]}]
set_property PACKAGE_PIN R16 [get_ports {adc9226_data[2]}]
set_property PACKAGE_PIN K21 [get_ports {adc9226_data[3]}]
set_property PACKAGE_PIN J20 [get_ports {adc9226_data[4]}]
set_property PACKAGE_PIN J21 [get_ports {adc9226_data[5]}]
set_property PACKAGE_PIN J22 [get_ports {adc9226_data[6]}]
set_property PACKAGE_PIN Y19 [get_ports {adc9226_data[7]}]
set_property PACKAGE_PIN AA19 [get_ports {adc9226_data[8]}]
set_property PACKAGE_PIN U20 [get_ports {adc9226_data[9]}]
set_property PACKAGE_PIN V20 [get_ports {adc9226_data[10]}]
set_property PACKAGE_PIN T21 [get_ports {adc9226_data[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc9226_clk]
set_property PACKAGE_PIN U21 [get_ports adc9226_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {VGCLK_tri_i[0]}]
set_property PACKAGE_PIN U10 [get_ports {VGCLK_tri_i[0]}]
