# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/maincontrol.xdc

# Block Designs: bd/main_control/main_control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control || ORIG_REF_NAME==main_control} -quiet] -quiet

# IP: bd/main_control/ip/main_control_processing_system7_0_0/main_control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_processing_system7_0_0 || ORIG_REF_NAME==main_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_0/main_control_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_0 || ORIG_REF_NAME==main_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_ps7_0_axi_periph_0/main_control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_50M_0/main_control_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_control_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_xbar_0/main_control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_xbar_0 || ORIG_REF_NAME==main_control_xbar_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_freq_out_0_0/main_control_freq_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_freq_out_0_0 || ORIG_REF_NAME==main_control_freq_out_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_1/main_control_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_1 || ORIG_REF_NAME==main_control_axi_gpio_0_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_2/main_control_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_2 || ORIG_REF_NAME==main_control_axi_gpio_0_2} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_3/main_control_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_3 || ORIG_REF_NAME==main_control_axi_gpio_0_3} -quiet] -quiet

# IP: bd/main_control/ip/main_control_ad9226_sample_0_0/main_control_ad9226_sample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_ad9226_sample_0_0 || ORIG_REF_NAME==main_control_ad9226_sample_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_dma_0_0/main_control_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_dma_0_0 || ORIG_REF_NAME==main_control_axi_dma_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axis_register_slice_0_0/main_control_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axis_register_slice_0_0 || ORIG_REF_NAME==main_control_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_xbar_1/main_control_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_xbar_1 || ORIG_REF_NAME==main_control_xbar_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_interconnect_0_0/main_control_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_interconnect_0_0 || ORIG_REF_NAME==main_control_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_40M_0/main_control_rst_ps7_0_40M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_40M_0 || ORIG_REF_NAME==main_control_rst_ps7_0_40M_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_142M_1/main_control_rst_ps7_0_142M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_142M_1 || ORIG_REF_NAME==main_control_rst_ps7_0_142M_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_pc_0/main_control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_pc_0 || ORIG_REF_NAME==main_control_auto_pc_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_us_0/main_control_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_us_0 || ORIG_REF_NAME==main_control_auto_us_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_pc_1/main_control_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_pc_1 || ORIG_REF_NAME==main_control_auto_pc_1} -quiet] -quiet

# XDC: bd/main_control/main_control_ooc.xdc
