# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/main_control_ad9226_sample_0_0.xci
# IP: The module: 'main_control_ad9226_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: E:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/main_control_ad9226_sample_0_0.xci
# IP: The module: 'main_control_ad9226_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/zhuobin/backup/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_ad9226_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
