
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2018.3
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_RCLEAR_DEVICE_ID,
		XPAR_RCLEAR_BASEADDR,
		XPAR_RCLEAR_INTERRUPT_PRESENT,
		XPAR_RCLEAR_IS_DUAL
	},
	{
		XPAR_VGCLK_DEVICE_ID,
		XPAR_VGCLK_BASEADDR,
		XPAR_VGCLK_INTERRUPT_PRESENT,
		XPAR_VGCLK_IS_DUAL
	},
	{
		XPAR_VGDATEN_DEVICE_ID,
		XPAR_VGDATEN_BASEADDR,
		XPAR_VGDATEN_INTERRUPT_PRESENT,
		XPAR_VGDATEN_IS_DUAL
	},
	{
		XPAR_VGSDATA_DEVICE_ID,
		XPAR_VGSDATA_BASEADDR,
		XPAR_VGSDATA_INTERRUPT_PRESENT,
		XPAR_VGSDATA_IS_DUAL
	}
};


