# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/firmware/XILINX/demo/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_xbar_1/main_control_xbar_1.xci
# IP: The module: 'main_control_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/firmware/XILINX/demo/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_xbar_1/main_control_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_control_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/firmware/XILINX/demo/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_xbar_1/main_control_xbar_1.xci
# IP: The module: 'main_control_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/firmware/XILINX/demo/test_control/test_control.srcs/sources_1/bd/main_control/ip/main_control_xbar_1/main_control_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_control_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
